- hosts: target
  tasks:
  - name: "do apt update"
    become: true
    apt:
      update_cache: yes
  
  - name: "necessary packages"
    apt: 
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present

  - name: DockerリポジトリのGPGキーをシステムに追加します
    become: true
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: DockerリポジトリをAPTソースに追加します
    become: true
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: apt updateを実行します
    become: true
    apt:
      update_cache: yes

  - name: Add Docker apt repository
    apt_repository:
      repo: "deb [Arch=AMD64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
      filename: docker

  - name: Install docker
    apt:
      name: docker-ce
      state: present

  - meta: flush_handlers